---
.github/workflows/ci.yml:
  beaker_fact_matrix: {}
  excludes: []
  pidfile_workaround: false
.travis.yml:
  delete: true
Gemfile:
  puppet_version: '~> 6.0'
  required:
    ':test':
      - gem: voxpupuli-test
        version: '~> 2.1'
      - gem: simplecov-console
    ':development': []
    ':system_tests':
      - gem: puppet_metadata
        version: '~> 0.3.0'
      - gem: voxpupuli-acceptance
    ':release':
      - gem: github_changelog_generator
        git: https://github.com/voxpupuli/github-changelog-generator
        branch: voxpupuli_essential_fixes
      - gem: puppet-blacksmith
      - gem: voxpupuli-release
      - gem: puppet-strings
        version: '>= 2.2'
Rakefile:
  config.user: opus-codium
  puppet_strings_patterns: []
