---
.travis.yml:
  test_with_debian_puppet:
    stretch: false
    buster: false
Gemfile:
  common:
    ':test':
      - gem: facter
        version: '~> 2.0'
        version_var: FACTER_GEM_VERSION
      - gem: metadata-json-lint
      - gem: puppet-lint-classes_and_types_beginning_with_digits-check
      - gem: puppet-lint-leading_zero-check
      - gem: puppet-lint-param-docs
      - gem: puppet-lint-param-types
      - gem: puppet-lint-trailing_comma-check
      - gem: puppet-lint-unquoted_string-check
      - gem: puppet-lint-variable_contains_upcase
      - gem: puppet-lint-version_comparison-check
      - gem: puppet-strings
      - gem: puppetlabs_spec_helper
      - gem: rspec-puppet-facts
      - gem: rubocop
Rakefile:
  common_disabled_lint_checks:
    - disable_140chars
    - disable_documentation
