name: noop run

on:
  pull_request: {}
  push:
    branches:
      - master

jobs:
  unit:
    runs-on: ubuntu-latest
    name: Run msync --noop against all modules
    steps:
      - uses: actions/checkout@v4
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: Run msync --noop
        run: bundle exec msync update --noop --git-base=https://github.com/
  metadata_json_deps:
    runs-on: ubuntu-latest
    name: Run metadata_json_deps on all modules
    steps:
      - uses: actions/checkout@v4
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: Run msync --noop
        run: bundle exec msync clone --git-base=https://github.com/
      - run: bundle exec rake metadata_deps

  tests:
    needs:
      - unit
      - metadata_json_deps
    runs-on: ubuntu-latest
    name: Test suite
    steps:
      - run: echo Test suite completed
